KLEI     1 return {
	override_enabled = true,
	overrides = {
		angrybees = "rare",
		autumn = "longseason",
		beefalo = "often",
		berrybush = "often",
		carrot = "mostly",
		carrots_regrowth = "fast",
		chess = "rare",
		day = "longday",
		deciduoustree_regrowth = "fast",
		evergreen_regrowth = "fast",
		flint = "often",
		flowers_regrowth = "fast",
		grass = "mostly",
		houndmound = "rare",
		merm = "rare",
		moon_carrot = "often",
		moon_spiders = "rare",
		mushroom = "often",
		ocean_waterplant = "ocean_rare",
		rabbits = "often",
		rabbits_setting = "often",
		regrowth = "fast",
		rock = "often",
		sapling = "often",
		spring = "longseason",
		trees = "mostly",
		walrus = "rare",
	},
}